baseURL = "https://mozanunal.com/"
author = "M.Ozan Unal"
copyright = "Copyright © 2014–2024"
paginate = 40
languageCode = "en"

googleAnalytics = 'G-007KSW65JL'
DefaultContentLanguage = "en"
enableInlineShortcodes = true

# ------------------------------
theme = "paper"
title = "M.Ozan Unal"

[permalinks]
  posts = "/:year/:month/:filename"

[params]
  color = 'gray'

  twitter = 'MOzanUnal'
  github = 'mozanunal'
  instagram = 'mozanunal'

  avatar = 'mehmetozanunal@gmail.com'
  name = 'M.Ozan Unal'
  bio = 'ML & Data Engineer. Expertise in big data and deep learning'
  disableHLJS = true
  monoDarkIcon = true
  math = true
# ------------------------------
# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      footnote = true
  [markup.highlight]
    style = "dracula"
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    tabWidth = 4
    noClasses = true


[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

[taxonomies]
  category = "categories"
  tag = "tags"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

